### ISSUE TITLE
"Could not resolve the rosdep key 'rosaria" while integrating 2 packages in the build farm

### ISSUE THREAD

**Issue by amineHorseman** [ros/rosdistro#12342]
Hi, 

Yestreday I integrated two new packages, but it seems that it made a failure during the integration process in the build farm.

I can understand the error for xenial since `rosaria` doesn't exist in `distibution.yam`l file of kinetic. 

But I don't understand why the same error occurred for trusty (because rosaria package is present `distibution.yaml` file for both indigo and jade)

Here's the build log (truncated): 

```
Step 23 : CMD rosdep update && PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH python3 -u /tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py --rosdistro-name indigo --workspace-root /tmp/catkin_workspace --os-name ubuntu --os-code-name trusty --arch amd64 --distribution-repository-urls http://repositories.ros.org/ubuntu/testing --distribution-repository-key-files /tmp/keys/0.key --dockerfile-dir /tmp/docker_build_and_install && PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH python3 -u /tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py --rosdistro-name indigo --workspace-root /tmp/catkin_workspace --os-name ubuntu --os-code-name trusty --arch amd64 --distribution-repository-urls http://repositories.ros.org/ubuntu/testing --distribution-repository-key-files /tmp/keys/0.key --dockerfile-dir /tmp/docker_build_and_test --testing
 ---> Running in 9ba9f849c31f
 ---> f40aee10c2ed
Removing intermediate container 9ba9f849c31f
Successfully built f40aee10c2ed
+ echo # END SECTION
# END SECTION
+ echo # BEGIN SECTION: Run Dockerfile - generating devel tasks
# BEGIN SECTION: Run Dockerfile - generating devel tasks
+ rm -fr <http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/docker_build_and_install>
+ rm -fr <http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/docker_build_and_test>
+ mkdir -p <http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/docker_build_and_install>
+ mkdir -p <http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/docker_build_and_test>
+ docker run --rm --cidfile=<http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/docker_generating_dockers/docker.cid> -e=HOME=/home/buildfarm -v <http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/ros_buildfarm>:/tmp/ros_buildfarm:ro -v <http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/catkin_workspace>:/tmp/catkin_workspace:ro -v <http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/docker_build_and_install>:/tmp/docker_build_and_install -v <http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/docker_build_and_test>:/tmp/docker_build_and_test -v /home/jenkins-slave/.ccache:/home/buildfarm/.ccache devel_task_generation.indigo_pioneer_bringup
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
Add distro "groovy"
Add distro "hydro"
Add distro "indigo"
Add distro "jade"
Add distro "kinetic"
updated cache in /home/buildfarm/.ros/rosdep/sources.cache
Crawling for packages in workspace '/tmp/catkin_workspace/src'
Found the following packages:
  - pioneer_bringup
Package maintainer emails: bendahmane.amine@gmail.com
Always install the following generic dependencies:
  - build-essential
  - python3
  - ros-indigo-catkin
Identified the following build dependencies (ignoring packages available from source):
  - catkin
Resolved the dependencies to the following binary packages:
  - ros-indigo-catkin
Identified the following run and test dependencies (ignoring packages available from source):
  - geometry_msgs
  - lms1xx
  - rosaria
  - rospy
  - usb_cam
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 232, in resolve_names
    rosdep_key, view, installer, os_name, os_code_name)
  File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 81, in resolve_for_os
    d = view.lookup(rosdep_key)
  File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 187, in lookup
    return self.rosdep_defs[rosdep_name]
KeyError: 'rosaria'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 248, in <module>
    main()
  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 122, in main
    run_and_test_depends, **context)
  File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 235, in resolve_names
    "Could not resolve the rosdep key '%s'" % rosdep_key)
RuntimeError: Could not resolve the rosdep key 'rosaria'
Build step 'Execute shell' marked build as failure
[WARNINGS]Skipping publisher since build result is FAILURE
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing GoogleTest-1.6
[xUnit] [INFO] - [GoogleTest-1.6] - No test report file(s) were found with the pattern 'catkin_workspace/test_results/**/*.xml' relative to '<http://build.ros.org/job/Idev__pioneer_bringup__ubuntu_trusty_amd64/ws/'> for the testing framework 'GoogleTest-1.6'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'GoogleTest-1.6'?
[xUnit] [WARNING] - No test reports found for the metric 'GoogleTest' with the resolved pattern 'catkin_workspace/test_results/**/*.xml'.
[xUnit] [INFO] - Skipping the metric tool processing.
[xUnit] [INFO] - There are errors when processing test results.
[xUnit] [INFO] - Skipping tests recording.
```

**Comment by dirk-thomas** [comment]
The devel job for `pioneer_bringup` needs to install its dependencies. But `rosaria` has not been released yet. It only has a doc and source entry but no release entry and therefore no Debian package which can be installed in order to test downstream packages. If you want the devel jobs for `pioneer_bringup` to pass you need to release all its dependencies.
