### ISSUE TITLE
Error catkin_make and catkin_create_pkg Melodic

### ISSUE THREAD

**Issue by LuisYordano** [ros/rosdistro#19384]
Hi,
In ros melodic there is a error in catkin_make (version actual 0.4.9-100):
--------------------------------------------------------------------
luis@robtech:~/catkin_ws$ catkin_make
Base path: /home/luis/catkin_ws
Source space: /home/luis/catkin_ws/src
Build space: /home/luis/catkin_ws/build
Devel space: /home/luis/catkin_ws/devel
Install space: /home/luis/catkin_ws/install
Creating symlink "/home/luis/catkin_ws/src/CMakeLists.txt" pointing to "/opt/ros/melodic/share/catkin/cmake/toplevel.cmake"
####
####
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (message):
  Search for 'catkin' in workspace failed (catkin_find_pkg catkin
  /home/luis/catkin_ws/src): Traceback (most recent call last):

    File "/usr/local/bin/catkin_find_pkg", line 6, in <module>
      from pkg_resources import load_entry_point
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3086, in <module>
      @_call_aside
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
      f(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
      working_set = WorkingSet._build_master()
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
      return cls._build_from_requirements(__requires__)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
      dists = ws.resolve(reqs, Environment())
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
      raise DistributionNotFound(req, requirers)

  pkg_resources.DistributionNotFound: The 'catkin-pkg==0.4.8' distribution
  was not found and is required by the application

-- Configuring incomplete, errors occurred!
See also "/home/luis/catkin_ws/build/CMakeFiles/CMakeOutput.log".
Invoking "cmake" failed

--------------------------------------------------------------------
luis@robtech:~/catkin_ws/src$ catkin_create_pkg multirobot rospy gazebo
Traceback (most recent call last):
  File "/usr/local/bin/catkin_create_pkg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'catkin-pkg==0.4.8' distribution was not found and is required by the application
--------------------------------------------------------------------

Could you tell me how to fix this error?

**Comment by clalancette** [comment]
In general, we ask that you please ask questions like this on https://answers.ros.org.  That way, we can have all answers in a single place that is easy to search.  It looks like you are missing some part of your installation, so when you open up your question, please provide all of the steps you did to install ROS, and the packages that you are trying to build.  I'm going to close this issue out for now.
