### ISSUE TITLE
Bug: Can't run nosetests on python3.11 - module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by Ryanf55** [ros/rosdistro#37844]
# Bug Report

OS: Ubuntu 23.04
Python: fresh `3.11.2` virtual environment
Version: Master, hash `a8f655c921835a521417b8dd4318da74eb067ab7`

## Steps to reproduce

```bash
cd rosdistro
python3 -m venv .venv
. .venv/bin/activate
python3 -m pip install -r tests/requirements.txt
nosetests
```

## Error logs

```
(.venv) ryan@ryan-B650-970:~/Development/rosdistro$ nosetests
Traceback (most recent call last):
  File "/home/ryan/Development/rosdistro/.venv/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
             ^^^^^^^^^^
  File "/home/ryan/Development/rosdistro/.venv/lib/python3.11/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/usr/lib/python3.11/unittest/main.py", line 101, in __init__
    self.parseArgs(argv)
  File "/home/ryan/Development/rosdistro/.venv/lib/python3.11/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/ryan/Development/rosdistro/.venv/lib/python3.11/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/Development/rosdistro/.venv/lib/python3.11/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/Development/rosdistro/.venv/lib/python3.11/site-packages/nose/loader.py", line 454, in loadTestsFromName
    return LazySuite(
           ^^^^^^^^^^
  File "/home/ryan/Development/rosdistro/.venv/lib/python3.11/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/usr/lib/python3.11/unittest/suite.py", line 22, in __init__
    self._tests = []
    ^^^^^^^^^^^
  File "/home/ryan/Development/rosdistro/.venv/lib/python3.11/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

```

## Attemped solutions

* Try installing a different version of python? Sadly, I can't install anything except 3.11.
  ```
  sudo apt-cache policy python3
python3:
  Installed: 3.11.2-1
  Candidate: 3.11.2-1
  Version table:
 *** 3.11.2-1 500
        500 http://us.archive.ubuntu.com/ubuntu lunar/main amd64 Packages
        100 /var/lib/dpkg/status
  ```
  Even the [python docs](https://docs.python.org/3/installing/index.html#work-with-multiple-versions-of-python-installed-in-parallel) say that's the way to install other python versions, but it doesn't work. 
  
  No solution [here](https://askubuntu.com/questions/1468624/error-installing-python-3-7-on-ubuntu-23-04) worked because the recommended PPA does not have any packages for 23.04.

**Comment by clalancette** [comment]
Since #36211, we are actually no longer use nosetests at all.  However, we haven't updated the CONTRIBUTING.md to show that fact.  See #38125
